# Generated by Django 3.1.7 on 2021-05-30 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='crntPostUser',
            fields=[
                ('uname', models.CharField(default='', max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='myreviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postuname', models.CharField(default='', max_length=100)),
                ('postimg', models.ImageField(upload_to='media')),
                ('postcaption', models.CharField(default='', max_length=200)),
                ('review', models.CharField(default='', max_length=300)),
            ],
        ),
    ]
