# Generated by Django 3.1.7 on 2021-05-30 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0002_crntpostuser_myreviews'),
    ]

    operations = [
        migrations.CreateModel(
            name='crntReviewUser',
            fields=[
                ('uname', models.CharField(default='', max_length=100, primary_key=True, serialize=False)),
            ],
        ),
    ]
