# Generated by Django 3.1.7 on 2021-05-30 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='curntUser',
            fields=[
                ('uname', models.CharField(default='', max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='postdb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(default='', max_length=100)),
                ('post_img', models.ImageField(upload_to='media')),
                ('post_caption', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='udetails',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
    ]
