# Generated by Django 3.1.7 on 2021-05-30 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_auto_20210530_1803'),
    ]

    operations = [
        migrations.AddField(
            model_name='postdb',
            name='post_reviews',
            field=models.CharField(default='', max_length=300),
        ),
    ]
