# Generated by Django 3.1.7 on 2021-05-31 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_postdb_post_reviews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postdb',
            name='post_caption',
            field=models.CharField(default='', max_length=300),
        ),
    ]
